//<auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DevHabit.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class Add_Habits : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Milestone_Current_Unit",
                schema: "devhabit",
                table: "Habits");

            migrationBuilder.DropColumn(
                name: "Milestone_Exists",
                schema: "devhabit",
                table: "Habits");

            migrationBuilder.DropColumn(
                name: "Milestone_Target_Unit",
                schema: "devhabit",
                table: "Habits");

            migrationBuilder.RenameColumn(
                name: "MilestoneTargetValue",
                schema: "devhabit",
                table: "Habits",
                newName: "MilestoneTarget");

            migrationBuilder.RenameColumn(
                name: "MilestoneCurrentValue",
                schema: "devhabit",
                table: "Habits",
                newName: "MilestoneCurrent");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "MilestoneTarget",
                schema: "devhabit",
                table: "Habits",
                newName: "MilestoneTargetValue");

            migrationBuilder.RenameColumn(
                name: "MilestoneCurrent",
                schema: "devhabit",
                table: "Habits",
                newName: "MilestoneCurrentValue");

            migrationBuilder.AddColumn<string>(
                name: "Milestone_Current_Unit",
                schema: "devhabit",
                table: "Habits",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "Milestone_Exists",
                schema: "devhabit",
                table: "Habits",
                type: "bit",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Milestone_Target_Unit",
                schema: "devhabit",
                table: "Habits",
                type: "nvarchar(100)",
                maxLength: 100,
                nullable: true);
        }
    }
}
