<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Asp.Versioning.Mvc" Version="8.1.1" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.15" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.15" />
    <PackageVersion Include="Microsoft.AspNetCore.JsonPatch" Version="9.0.14" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.14" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="9.0.13" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.14" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.14" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.14" />
    <PackageVersion Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.3" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.15.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.1" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.15.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.15.0" />
    <PackageVersion Include="Quartz" Version="3.18.1" />
    <PackageVersion Include="Quartz.Extensions.Hosting" Version="3.18.1" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="[10.21.0.135717,)" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="9.0.6" />
    <PackageVersion Include="System.Linq.Dynamic.Core" Version="1.7.2" />
    <PackageVersion Include="coverlet.collector" Version="6.0.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageVersion Include="xunit" Version="2.9.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
</Project>